// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY8qFtgyuq4m5UrMNoH2t4q-_5gvMp6mU',
    appId: '1:481055608603:web:f2b4e4e938491ca9358dbe',
    messagingSenderId: '481055608603',
    projectId: 'goodwill-83933',
    authDomain: 'goodwill-83933.firebaseapp.com',
    storageBucket: 'goodwill-83933.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsygct_Fd9N8qwFx0MtYI5SWLgNgfopxo',
    appId: '1:481055608603:android:5071c17110990c45358dbe',
    messagingSenderId: '481055608603',
    projectId: 'goodwill-83933',
    storageBucket: 'goodwill-83933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhr4QYU92F809s11m7q8LO9e7zcZ6YqZE',
    appId: '1:481055608603:ios:a741c31e1b1272c0358dbe',
    messagingSenderId: '481055608603',
    projectId: 'goodwill-83933',
    storageBucket: 'goodwill-83933.appspot.com',
    iosClientId: '481055608603-vogkghc6f9n3e4t5o777alp4cacfiie1.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodwill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhr4QYU92F809s11m7q8LO9e7zcZ6YqZE',
    appId: '1:481055608603:ios:a741c31e1b1272c0358dbe',
    messagingSenderId: '481055608603',
    projectId: 'goodwill-83933',
    storageBucket: 'goodwill-83933.appspot.com',
    iosClientId: '481055608603-vogkghc6f9n3e4t5o777alp4cacfiie1.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodwill',
  );
}
